//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M02_BasicEntities : DbContext
    {
        public M02_BasicEntities()
            : base("name=M02_BasicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M02_CommonSetting> M02_CommonSetting { get; set; }
        public virtual DbSet<M02_DefaultCommonSetting> M02_DefaultCommonSetting { get; set; }
        public virtual DbSet<M02_EmailSettings> M02_EmailSettings { get; set; }
    }
}
